# data
dataset_name: mosquito_alert_v0 # check mosquito/datasets/__init__.py
data_dir: data
batch_size: 64

# data augmentation
transform_name: mosquito_alert_v0 # check mosquito/transforms/__init__.py
input_size: 224

# optimization
num_epochs: 30
learning_rate: 3e-4
momentum: 0.996
weight_decay: 5e-4

# model
model_name: faster_rcnn # check mosquito/models/__init__.py
hidden_layer_size: 256

# logging
log_freq: 100

seed: 1